---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: frontend
  chart:
    git: ssh://git@github.com/akiyamasho/flux-practice
    ref: master
    path: charts/frontend
  values:
    image:
      repository: docker.io/akiyamasho/flux-practice-frontend
      tag: 1.0
